services:
  - type: web
    name: bcb-mobile-banking
    runtime: static
    buildCommand: npm install; npm run build
    staticPublishPath: build/web
    envVars:
      - key: FLUTTER_VERSION
        value: stable
